#!/bin/bash

# Setup script generated by setup_new_environment.py
# Generated: 2024-12-15T16:24:53.471796

# TODO: Start Vault server using setup_app.py

# Final setup steps
python setup_app.py
python init_db.py

# Run verification
python utils/setup/verify_deployment.py
