"""Add navigation categories

Revision ID: 6e392dee0a38
Revises: 
Create Date: 2024-12-04 19:26:51.528699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e392dee0a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_route_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_page_route_category', 'navigation_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_route_mapping', schema=None) as batch_op:
        batch_op.drop_constraint('fk_page_route_category', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
