"""Add user roles and other tables

Revision ID: 87a354dd604e
Revises: 6e392dee0a38
Create Date: 2024-12-04 21:47:36.118034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a354dd604e'
down_revision = '6e392dee0a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('route_roles',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['page_route_mapping.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'role_id')
    )
    op.drop_table('user_role')
    op.drop_table('page_visit')
    op.drop_table('page_route_roles')
    with op.batch_alter_table('navigation_category', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('page_route_mapping', schema=None) as batch_op:
        batch_op.alter_column('page_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('route',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_column('vzid')
        batch_op.drop_column('cngroup')
        batch_op.drop_column('employee_number')

    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('activity',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.alter_column('activity',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('cngroup', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('vzid', sa.VARCHAR(length=64), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('page_route_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('route',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('page_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('navigation_category', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('page_route_roles',
    sa.Column('page_route_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['page_route_id'], ['page_route_mapping.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('page_route_id', 'role_id')
    )
    op.create_table('page_visit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), nullable=True),
    sa.Column('route', sa.VARCHAR(length=256), nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status_code', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_table('route_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
