"""Add summary and icon fields to Project model and order field to Todo model

Revision ID: 9c1fbb290532
Revises: 960135e4e7ab
Create Date: 2024-12-06 16:42:54.573195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1fbb290532'
down_revision = '960135e4e7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
